commands:
  set:
    description: "top-level command for setting system parameters"
    flags: 
      - names: ["-v", "--verbose"]
        flag_type: "Modify"
        description: "Enable verbose output"
    subcommands:
      wallpaper:
        description: "Set the desktop wallpaper"
        run: "set_wallpaper"
        params:
          - name: "image_path"
            param_type: "String"
        flags:
          - names: ["--preview"]
            flag_type: "Overwrite"
            description: "Preview the wallpaper before applying"
